export const DISPLAY_ALERT = 'SHOW ALERT'
export const CLEAR_ALERT = 'CLEAR ALERT'

export const REGISTER_USER_BEGIN = 'REGISTER USER BEGIN'
export const REGISTER_USER_SUCCESS = 'REGISTER USER_SUCCESS'
export const REGISTER_USER_ERROR = 'REGISTER USER ERROR'

export const LOGIN_USER_BEGIN = 'REGISTER USER BEGIN'
export const LOGIN_USER_SUCCESS = 'REGISTER USER_SUCCESS'
export const LOGIN_USER_ERROR = 'REGISTER USER ERROR'

export const TOGGLE_SIDE_BAR = 'TOGGLE_SIDE_BAR'

export const LOG_OUT_USER = 'LOG_OUT_USER'